
# CyberDeaths Configuration

# If true, players will be shown their last coordinates and world name when they die
send_death_location: true

# World name aliases to show in the death point message
world_name_aliases:
  world: "the overworld"
  world_nether: "the nether"
  world_the_end: "the end"

# If true, player display names will be used in death messages
use_player_displaynames: true

# If true, the custom names of mobs will be used in death messages, if applicable
use_mob_displaynames: true

# Messages
messages:
  reloaded: "&aConfig reloaded!"
  died_at_coords: "&fYou died at &b%0, %1, %2&f in &7%3"
  # Death messages
  # &r will be added to the end of all display names
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
  deaths:
    block_explosion: "%0 blew up!"
    contact: "%0 was pricked to death!"
    contact_cactus: "%0 fell in a bed of cacti!"
    contact_sweet_berry_bush: "%0 picked too many sweet berries!"
    contact_pointed_dripstone: "%0 was impaled by dripstone!"
    cramming: "%0 died of claustrophobia!"
    custom: "%0 died mysteriously!"
    dragon_breath: "%0 inhaled too much dragon's breath!"
    drowning: "%0 drowned!"
    dryout: "%0 suffocated!"
    entity_attack: "%0 was slain by %1!"
    entity_attack_guardian: "%0 was zapped by %1!"
    entity_attack_elder_guardian: "%0 was zapped by %1!"
    entity_attack_weapon: "%0 was slain by %1 using &b%2!"
    entity_explosion: "%0 was blown up by %1!"
    entity_explosion_ghast: "%0 was fireballed by %1!"
    entity_sweep_attack: "%0 was swept away by %1!"
    entity_sweep_attack_weapon: "%0 was swept away by %1 using &b%2!"
    fall: "%0 took too big of a fall!"
    falling_block: "%0 was crushed by a falling block!"
    falling_block_anvil: "%0 was squashed by a falling anvil!"
    falling_block_pointed_dripstone: "%0 was impaled by falling dripstone!"
    fire_tick: "%0 was burnt to a crisp!"
    fire: "%0 burned to death!"
    fly_into_wall: "%0 slammed into a wall!"
    freeze: "%0 froze!"
    hot_floor: "%0 tried to dance on lava!"
    lava: "%0 tried to swim in lava!"
    lightning: "%0 was struck by lightning!"
    magic: "%0 was killed by magic!"
    magic_entity: "%0 was killed by the magic of %1!"
    melting: "%0 melted!"
    poison: "%0 was poisoned to death!"
    projectile: "%0 was shot!"
    projectile_entity: "%0 was shot by %1!"
    projectile_entity_blaze: "%0 was fireballed by %1!"
    projectile_entity_ghast: "%0 was fireballed by %1!"
    projectile_entity_weapon: "%0 was shot by %1 using &b%2!"
    projectile_entity_snowball: "%0 was pummeled %1!"
    projectile_entity_egg: "%0 was egged %1!"
    sonic_boom: "%0 took the Warden's sonic boom head on!"
    starvation: "%0 starved!"
    suffocation: "%0 suffocated in a block!"
    suicide: "%0 committed suicide!"
    suicide_weapon: "%0 committed suicide using &b%1!"
    thorns: "%0 was pricked to death by %1!"
    void: "%0 fell in the void!"
    wither: "%0 withered away!"
  death_default: "%0 died!"
  death_prefix: "&cDeath &8>&f "

# Entity names
# For entities not listed here, their default names will be used
# Entities that could never show up in a death message have been excluded
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
entity_names:
  allay: "Allay"
  axolotl: "Axolotl"
  bat: "Bat"
  bee: "Bee"
  blaze: "Blaze"
  camel: "Camel"
  cat: "Cat"
  cave_spider: "Cave Spider"
  chicken: "Chicken"
  cod: "Cod"
  cow: "Cow"
  creeper: "Creeper"
  dolphin: "Dolphin"
  donkey: "Donkey"
  drowned: "Drowned"
  elder_guardian: "Elder Guardian"
  ender_dragon: "Ender Dragon"
  enderman: "Enderman"
  endermite: "Endermite"
  evoker: "Evoker"
  fireball: "Fireball"
  firework: "Firework"
  fox: "Fox"
  frog: "Frog"
  ghast: "Ghast"
  giant: "Giant"
  glow_squid: "Glow Squid"
  goat: "Goat"
  guardian: "Guardian"
  hoglin: "Hoglin"
  horse: "Horse"
  husk: "Husk"
  illusioner: "Illusioner"
  interaction: "Interaction"
  iron_golem: "Iron Golem"
  llama: "Llama"
  magma_cube: "Magma Cube"
  mule: "Mule"
  mushroom_cow: "Mushroom Cow"
  ocelot: "Ocelot"
  panda: "Panda"
  parrot: "Parrot"
  phantom: "Phantom"
  pig: "Pig"
  piglin_brute: "Piglin Brute"
  piglin: "Piglin"
  pillager: "Pillager"
  primed_tnt: "TNT"
  polar_bear: "Polar Bear"
  pufferfish: "Pufferfish"
  rabbit: "Rabbit"
  ravager: "Ravager"
  salmon: "Salmon"
  sheep: "Sheep"
  shulker: "Shulker"
  silverfish: "Silverfish"
  skeleton_horse: "Skeleton Horse"
  skeleton: "Skeleton"
  slime: "Slime"
  sniffer: "Sniffer"
  snowball: "Snowball"
  snowman: "Snowman"
  spider: "Spider"
  squid: "Squid"
  stray: "Stray"
  strider: "Strider"
  tadpole: "Tadpole"
  trader_llama: "Trader Llama"
  tropical_fish: "Tropical Fish"
  turtle: "Turtle"
  vex: "Vex"
  villager: "Villager"
  vindicator: "Vindicator"
  wandering_trader: "Wandering Trader"
  warden: "Warden"
  witch: "Witch"
  wither_skeleton: "Wither Skeleton"
  wither: "Wither"
  wolf: "Wolf"
  zoglin: "Zoglin"
  zombie_horse: "Zombie Horse"
  zombie_villager: "Zombie Villager"
  zombie: "Zombie"
  zombified_piglin: "Zombified Piglin"

# Changing this value will wipe your config!
config_version: 1